#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xml-resolver
Version  : 1.2
Release  : 1
URL      : http://mirror.metrocast.net/apache/xerces/xml-commons/xml-commons-resolver-1.2.tar.gz
Source0  : http://mirror.metrocast.net/apache/xerces/xml-commons/xml-commons-resolver-1.2.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-xml-resolver-data = %{version}-%{release}
Requires: mvn-xml-resolver-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-xml-resolver package.
Group: Data

%description data
data components for the mvn-xml-resolver package.


%package license
Summary: license components for the mvn-xml-resolver package.
Group: Default

%description license
license components for the mvn-xml-resolver package.


%prep
%setup -q -n xml-commons-resolver-1.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-xml-resolver
cp LICENSE.resolver.txt %{buildroot}/usr/share/package-licenses/mvn-xml-resolver/LICENSE.resolver.txt
cp src/org/apache/xml/resolver/LICENSE.resolver.txt %{buildroot}/usr/share/package-licenses/mvn-xml-resolver/src_org_apache_xml_resolver_LICENSE.resolver.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
/usr/share/java/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-xml-resolver/LICENSE.resolver.txt
/usr/share/package-licenses/mvn-xml-resolver/src_org_apache_xml_resolver_LICENSE.resolver.txt
